# Bug

Corrija los dos errores en el c√≥digo para que pueda ejecutarse.

```python
print("Uno, dos, tres...')
prnt("... cuatro, cinco, seis.")
```